language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update
- sudo apt-get install nodejs npm
- sudo npm config set registry http://registry.npmjs.org/
- sudo npm install -g node-gyp
script: make release && make
